# Generated by Django 2.2.2 on 2019-07-04 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20190704_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomschedule',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='roomschedule',
            name='is_rejected',
        ),
    ]
